fallback = ''

[matching]
'discord' = ''
'balena-etcher' = ''
'Steam' = ''
'vlc' = ''
'mpv' = ''
'feh' = ''
'org.qbittorrent.qBittorrent' = ''
'Thunderbird' = ''
'thunderbird' = ''
'Postman' = ''
'Insomnia' = ''
'Bitwarden' = ''
'Google-chrome' = ''
'Chromium' = ''
'Slack' = ''
'Code' = ''
'code-oss' = ''
'Spotify' = ''
'/(?i)Github.*Firefox/' = ''
'firefox' = ''
'Nightly' = ''
'firefoxdeveloperedition' = ''
'/nvim ?\w*/' = ''
'/tut /' = ''
'/tuir/' = ''
'Alacritty' = ''
'foot' = ''
'dolphin' = ''
'lagrange' = ''
'TelegramDesktop' = ''
'/Zoom Meeting/' = ''
'dino' = ''
'org.gajim.Gajim' = ''
